Django_Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Django_Blog import settings
from blog import views
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^admin/', include(admin.site.urls)),
                  url(r'^accounts/', include(admin.site.urls)),
                  url(r'^$', views.post_list, name='post_list'),
                  url(r'^contact/', views.contact, name='contact'),
                  url(r'^apps/(?P<post_id>[0-9]+)/$', views.post_page, name='post_detail'),

                  url(r'^twitter/', include('top_twitter.urls')),

                  # http://docs.djangoproject.com/en/dev/howto/static-files/
                  # This method is inefficient and insecure.
                  # Do not use this in a production setting.
                  # Use this only for development.
                  url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                      {'document_root': settings.MEDIA_ROOT}),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.core import validators

from material import *


class App(models.Model):
    id = models.IntegerField(primary_key=True,
                             unique=True,
                             editable=False,
                             auto_created=True,
                             db_index=True)

    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=100)
    description = models.TextField(default='')
    article = models.TextField(default='')

    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,
                                          null=True,
                                          default=timezone.now)

    link_source = models.CharField(max_length=200,
                                   default='',
                                   validators=[validators.URLValidator()])
    link_apk = models.CharField(max_length=200,
                                default='',
                                validators=[validators.URLValidator()])

    preview_image = models.ImageField(upload_to='uploads/images/previews/',
                                      default='',
                                      help_text='Preview image. Only 1600x800 allowed')

    icon = models.ImageField(upload_to='uploads/images/icons/',
                             default='',
                             help_text='Small icon')

    # TODO create ColorPicker widget
    color_primary = models.CharField(max_length=7, default='#000000')
    color_secondary = models.CharField(max_length=7, default='#000000')

    def publish(self):
        self.published_date = timezone.now
        self.save()

    def __str__(self):
        return self.title


class Screenshot(models.Model):
    file = models.ImageField(upload_to='uploads/images/screenshots')
    page = models.ForeignKey('App')

blog/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(label='name', max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()

blog/views.py
from django.shortcuts import render
from django.core.mail import mail_admins, send_mail
from django.template import RequestContext

from .models import App


def post_list(request):
    apps = App.objects.order_by('title')
    return render(request, 'blog/post_list.html', {'apps': apps}, RequestContext(request))


def post_page(request, post_id):
    app = App.objects.get(id=post_id)
    return render(request, 'blog/post_page.html', {'app': app}, RequestContext(request))


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        subject = request.POST.get('subject', '')
        message = request.POST.get('message', '')
        sender = request.POST.get('email', '')

        recipients = ['cup.cake@inbox.ru']

        # mail_admins(subject, message, fail_silently=True)
        send_mail(subject,
                  "Name: " + name + "\n" + "Email: " + sender + "\n" + message,
                  sender, recipients, fail_silently=True)

        return render(request, 'blog/contact.html', {'sent_successful': True}, RequestContext(request))

    return render(request, 'blog/contact.html', {'sent_successful': False}, RequestContext(request))

templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.teal-red.min.css"/>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <script src="https://storage.googleapis.com/code.getmdl.io/1.1.3/material.min.js"></script>

    <title>Portfolio</title>

    {% block head %}
    {% endblock %}
</head>
<body>

<style>
    #drawer_card {
        min-height: 20%;
        max-height: 20%;
        width: 100%;
        background: #009688;
        color: white;
        border-radius: 0;
    }

    .mdl-layout__drawer {
        border-right: 0;
    }
    .mdl_card__title{
        background-size: cover;
    }
    .mdl-card--expand{
        background-size: cover;
    }
</style>

<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <span class="mdl-layout-title">Roman Svyatnenko</span>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <!-- Navigation. We hide it in small screens. -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                <a class="mdl-navigation__link" href="http://0.0.0.0/">Home</a>
                <a class="mdl-navigation__link" href="http://0.0.0.0/apps">My apps</a>
                <a class="mdl-navigation__link" href="http://github.com">Github</a>
                <a class="mdl-navigation__link" href="http://0.0.0.0/about">About</a>
            </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <div id="drawer_card" class="mdl-card mdl-shadow--4dp mdl-layout-title">
            <h3></h3>
        </div>

        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="http://0.0.0.0/">Home</a>
            <a class="mdl-navigation__link" href="http://0.0.0.0/apps">My apps</a>
            <a class="mdl-navigation__link" href="http://github.com">Github</a>
            <a class="mdl-navigation__link" href="http://0.0.0.0/contact">Contact</a>
            <a class="mdl-navigation__link" href="http://0.0.0.0/about">About</a>
        </nav>
    </div>
    <main class="mdl-layout__content">
        <div class="page-content" align="center">
            <!-- Your content goes here -->
            {% block content %}
            {% endblock %}
        </div>
    </main>
</div>

</body>
</html>

templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load staticfiles %}


{% block head %}
{% endblock %}


{% block content %}

    <style>
        h1, input::-webkit-input-placeholder, button {
            font-family: 'roboto', sans-serif;
            transition: all 0.3s ease-in-out;
        }

        h1 {
            height: 100px;
            width: 100%;
            font-size: 30pt;
            background: #18aa8d;
            color: white;
            line-height: 150%;
            border-radius: 3px 3px 0 0;
            box-shadow: 0 2px 5px 1px rgba(0, 0, 0, 0.2);
        }

        form {
            box-sizing: border-box;
            width: 40%;
            margin: 0 auto 0;
            box-shadow: 2px 2px 5px 1px rgba(0, 0, 0, 0.2);
            padding-bottom: 40px;
            border-radius: 3px;
        }

        form h1 {
            box-sizing: border-box;
            padding: 20px;
        }

        input {
            margin: 40px 25px;
            width: 80%;
            display: block;
            border: none;
            padding: 10px 0;
            border-bottom: solid 1px #1abc9c;
            transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
            background-size: 200px 100%;
            background: linear-gradient(to bottom, rgba(255, 255, 255, 0) 96%, #1abc9c 4%) no-repeat -200px 0;
            color: #0e6252;
        }

        input:focus, input:valid {
            box-shadow: none;
            outline: none;
            background-position: 0 0;
        }

        input:focus::-webkit-input-placeholder, input:valid::-webkit-input-placeholder {
            color: #1abc9c;
            font-size: 11px;
            transform: translateY(-20px);
            visibility: visible !important;
        }

        button {
            border: none;
            background: #1abc9c;
            cursor: pointer;
            border-radius: 3px;
            padding: 6px;
            width: 80%;
            color: white;
            margin-left: 25px;
            box-shadow: 0 3px 6px 0 rgba(0, 0, 0, 0.2);
        }

        button:hover {
            transform: translateY(-3px);
            box-shadow: 0 6px 6px 0 rgba(0, 0, 0, 0.2);
        }

        .follow {
            width: 42px;
            height: 42px;
            border-radius: 50px;
            background: #03A9F4;
            display: inline-block;
            margin: 50px calc(50% - 21px);
            white-space: nowrap;
            padding: 13px;
            box-sizing: border-box;
            color: white;
            transition: all 0.2s ease;
            font-family: Roboto, sans-serif;
            text-decoration: none;
            box-shadow: 0 5px 6px 0 rgba(0, 0, 0, 0.2);
        }

        .follow i {
            margin-right: 20px;
            transition: margin-right 0.2s ease;
        }

        .follow:hover {
            width: 134px;
            transform: translateX(-50px);
        }

        .follow:hover i {
            margin-right: 10px;
        }

        .mdl-textfield {
            width: 80%;
        }

        .mdl-js-snackbar {
            max-width: 100%;
        }

        .mdl-js-snackbar > .mdl-snackbar__text {
            width: 100%;
        }

    </style>

    {% comment %} Contact form {% endcomment %}
    <iframe name="blank_frame" style="display:none;"></iframe>
    <form action="/contact/" method="post" target="blank_frame">
        {% csrf_token %}

        <h1>Contact me</h1>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <input name="name" class="mdl-textfield__input" type="text" id="name">
            <label class="mdl-textfield__label" for="name">Name</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <input name="subject" class="mdl-textfield__input" type="text" id="subject">
            <label class="mdl-textfield__label" for="name">Subject</label>
        </div>

        <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
            <input name="email" class="mdl-textfield__input" type="email" id="email">
            <label class="mdl-textfield__label" for="name">Email</label>
            <span class="mdl-textfield__error">Incorrect email address!</span>
        </div>

        <div class="mdl-textfield mdl-js-textfield">
            <textarea name="message" class="mdl-textfield__input" type="text" rows="5" id="message"></textarea>
            <label class="mdl-textfield__label" for="message">Message</label>
        </div>

        <!-- Colored raised button -->
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
                type="submit" value="Submit" onclick="showToast();">
            Send
        </button>
    </form>

    <a class="follow" href="https://twitter.com/ai_simple" target="_blank"><i class="fa fa-twitter"></i>Follow Me</a>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400' rel='stylesheet' type='text/css'>


    {# Material Desin Toast #}
    <div id="toast" class="mdl-js-snackbar mdl-snackbar">
        <div class="mdl-snackbar__text"></div>
        <button class="mdl-snackbar__action" type="button">Undo</button>
    </div>

    <script>
        function showToast() {
            var snackbarContainer = document.querySelector('#toast');
            snackbarContainer.MaterialSnackbar.showSnackbar(
                    {
                        message: 'Successfully sent'
                    }
            );
        }
    </script>

{% endblock content %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% include STATIC_URL %}


{% block content %}
    <script type="text/javascript">
        function openInNewTab(url) {
            var win = window.open(url, '_blank');
            win.focus();
        }
    </script>

    <style>
        html, body {
            height: 100%;
            width: 100%;
            margin: 0;
        }

        .mdl-card-wide.mdl-card {
            width: 800px;
            height: auto;

            margin: 2%;

            overflow: visible;
        }

        .mdl-card-wide > .mdl-card__title {
            color: #fff;

            position: relative;

            height: 400px;
            width: 100%;
            background-size: cover;
        }

        .mdl-card-wide > .mdl-card__supporting-text {
            margin-right: 40px;
        }

        .mdl-button--fab {
            position: absolute;
            right: 16px;
            top: 372px;
        }

        .mdl-card-wide > .mdl-card__menu {
            color: #fff;
        }

        .content-grid {
            max-width: 80%;
        }
    </style>

        {% for app in apps %}
            <!-- Wide card with share menu button -->
                <div class="mdl-card-wide mdl-card mdl-shadow--8dp">
                    <div class="mdl-card__title"
                         style="background: url({{ app.preview_image.url }})  no-repeat;
                                 background-size: 100% 100%">

                        <a style="position:absolute; width: 100%; height: 100%;"
                           href="{{ SITE_URL }}/apps/{{ app.id }}">
                        </a>

                        <h2 class="mdl-card__title-text">
                            {{ app.title }}
                        </h2>

                        <!-- Colored FAB button -->
                        <button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored"
                                onclick="openInNewTab('{{ app.link_source }}')">
                            <i class="material-icons">code</i>
                        </button>
                    </div>

                    <div class="mdl-card__supporting-text" align="left">
                        {{ app.description }}
                    </div>

                    <div class="mdl-card__menu">
                        <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
                            <!-- Right aligned menu below button -->
                            <button id="demo-menu-lower-right_{{ app.id }}"
                                    class="mdl-button mdl-js-button mdl-button--icon">
                                <i class="material-icons">more_vert</i>
                            </button>

                            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
                                for="demo-menu-lower-right_{{ app.id }}">
                                <li class="mdl-menu__item">Share</li>
                                <li class="mdl-menu__item">Read more</li>
                                <li disabled class="mdl-menu__item">Download .apk</li>
                                <li class="mdl-menu__item">Github</li>
                            </ul>
                        </button>
                    </div>
                </div>

            {# Get all related Objects (Screenshots) from class #}
            {#        {% for screenshot in app.screenshot_set.all %}#}
            {#            {{ screenshot.file.url }}#}
            {#            <br>#}
            {#        {% endfor %}#}

        {% endfor %}

{% endblock content %}

templates/blog/post_page.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% include STATIC_URL %}


{% block content %}

    <!-- Wide card with share menu button -->
    <style>
        html, body {
            height: 100%;
            width: 100%;
            margin: 0;
        }

        .mdl-card-wide.mdl-card {
            width: 60%;
            height: auto;
            margin: 2%;
            overflow: visible;
            max-width: 100%;
        }

        .mdl-card-wide > .mdl-card__title {
            color: #fff;
            height: 150px;
            width: 100%;
        }

        .mdl-card-wide > .mdl-card__title > .title {
            color: #fff;

            margin-left: 15%;
            margin-top: 50px;
        }

        .mdl-card__media {
            background-color: inherit;
            height: auto;
            width: 100%;

            padding: 7% 5% 2%;
        }

        .mdl-button--fab {
            position: absolute;
            right: 5%;
            top: 175px;
        }

        .app_icon {
            width: 100px;
            height: 100px;
            border-radius: 100px;
            -webkit-border-radius: 100px;
            -moz-border-radius: 100px;

            /* Shadow */
            box-shadow: 0 0 8px rgba(0, 0, 0, .8);
            -webkit-box-shadow: 0 0 8px rgba(0, 0, 0, .8);
            -moz-box-shadow: 0 0 8px rgba(0, 0, 0, .8);

            position: absolute;
            top: 100px;
            left: 5%;
        }

        .app_icon img {
        }

        .mdl-card-wide > .mdl-card__menu {
            color: #fff;
        }

        blockquote {
            display: block;
            background: inherit;
            padding: 15px 20px 15px 55px;
            margin-left: 2%;
            margin-right: 2%;
            position: relative;

            /*Font*/
            font-family: 'Lato', sans-serif;
            font-size: 14px;
            line-height: 1.2;
            color: #626262;
            text-align: justify;

            /*Borders - (Optional)*/
            border-left: 15px solid #607D8B;
            border-right: 2px solid #607D8B;

            /*Box Shadow - (Optional)*/
            -moz-box-shadow: 2px 2px 15px #ccc;
            -webkit-box-shadow: 2px 2px 15px #ccc;
            box-shadow: 2px 2px 15px #ccc;
        }

        blockquote::before {
            content: "\201C"; /*Unicode for Left Double Quote*/

            /*Font*/
            font-family: Georgia, serif;
            font-size: 60px;
            font-weight: bold;
            color: #999;

            /*Positioning*/
            position: absolute;
            left: 10px;
            top: 5px;
        }

        blockquote::after {
            /*Reset to make sure*/
            content: "";
        }

        blockquote a {
            text-decoration: none;
            background: #eee;
            cursor: pointer;
            padding: 0 3px;
            color: #607D8B;
        }

        blockquote a:hover {
            color: #666;
        }

        blockquote em {
            font-style: italic;
        }

    </style>

    <div class="mdl-card-wide mdl-card">

        <div class="mdl-card__title mdl-shadow--16dp"
             style="background-color: {{ app.color_primary }}">

            <div class="title">
                <h2>
                    {{ app.title }}
                </h2>
            </div>

            <div class="app_icon" style="/background: white">
                <img src="http://207.244.95.136/images/lock.png" height="100%" width="100%">
            </div>

            <!-- Colored FAB button -->
            <!-- <button class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
                 <i class="material-icons">code</i>
             </button>-->
        </div>

        <!-- <div class="mdl-card__actions mdl-card--border">
             <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                 Contact
             </a>
         </div>-->

        <div class="mdl-card__media mdl-shadow--16dp">
            <p align="left">
                {{ app.description }}
            </p>

            {{ app.article|safe }}

            {% for screenshot in app.screenshot_set.all %}
                <img src="{{ screenshot.file.url }}"
                     style="height:auto; max-width: 30%; padding-right: 5%; padding-left: 5%; padding-top: 2%">
            {% endfor %}

        </div>
    </div>

{% endblock content %}